TOOLS:
  WES:
#  - CLC
  - CNVnator
#  - ExomeDepth
#  - GermlineCNVCaller
#  - PennCNV3
  WGS:
#  - CLC
  - CNVnator
#  - GermlineCNVCaller
#  - PennCNV3

human_reference:          resources/sequence/ref.fa
chromosome_sequences_dir: resources/chromosome_sequences
dbsnp:                    resources/known_sites/dbsnp_138.b37.vcf.gz
mills:                    resources/known_sites/Mills_and_1000G_gold_standard.indels.b37.vcf.gz
indels1k:                 resources/known_sites/1000G_phase1.indels.b37.vcf.gz
snps1k:                   resources/known_sites/1000G_phase1.snps.high_confidence.b37.vcf.gz

multiqc_config:
  general:    resources/multiqc_config.yaml

bed:
  WES_probes:   resources/regions/S04380110_Covered_BED.bed
  WES_strict:   resources/regions/Broad_exomes.bed
  WGS_mappable: resources/regions/WGS_mappable_regions.bed

pon:
  CNVnator: ~

