TOOLS:
  WES:
  - cn.MOPS
  - CNVkit
  - CODEX2
  - ExomeDepth
  - GATK_gCNV 
  - Manta
  WGS:
  - cn.MOPS
#  - CNVkit
  - CNVnator
  - ControlFREEC
  - DELLY
  - Lumpy
  - GATK_gCNV
  - Manta
#  - SvABA
#  - TIDDIT

human_reference:          resources/hg19/sequence/ref.fa
sequence_dict:            resources/hg19/sequence/ref.dict
chromosome_sequences_dir: resources/chromosome_sequences
chromosome_lengths:       resources/hg19.len
dbsnp:                    resources/hg19/known_sites/dbsnp_138.b37.vcf.gz
mills:                    resources/hg19/known_sites/Mills_and_1000G_gold_standard.indels.b37.vcf.gz
indels1k:                 resources/hg19/known_sites/1000G_phase1.indels.b37.vcf.gz
snps1k:                   resources/hg19/known_sites/1000G_phase1.snps.high_confidence.b37.vcf.gz
refFlat:                  resources/refFlat.txt

gatk_conda_env: /home/projects/cu_10047/people/filipev/.conda/envs/gatk_4.1.0.0

multiqc_config:
  general: resources/multiqc_config.yaml

bed:
  WES_probes:   resources/hg19/regions/S04380110_Covered_BED.bed
  WES_strict:   resources/hg19/regions/Broad_exomes.bed
  WGS_mappable: resources/hg19/regions/WGS_mappable_regions.bed

pon:
  WES: resources/PoN/WES
  WGS: resources/PoN/WGS
