##
## Config file for snakemake CNV callers benchmarking workflow. 
##

## Fill in with the tools to run. If a tool is used for both WES and WGS samples, put it in both lists.
# A sample is determined as either WES or WGS from its name; A WES sample must contain the string 'WES' in the file name and likewise for WGS samples.
TOOLS:
  WES:
  - cn.MOPS
  - CNVkit
  - CODEX2
  - ExomeDepth
  - GATK_gCNV 
  - Manta
  WGS:
  - cn.MOPS
  - CNVnator
  - ControlFREEC
  - DELLY
  - Lumpy
  - GATK_gCNV
  - Manta

## Reference genome specific files
human_reference:          resources/hg19/sequence/ref.fa
sequence_dict:            resources/hg19/sequence/ref.dict
chromosome_sequences_dir: resources/chromosome_sequences
chromosome_lengths:       resources/hg19.len
dbsnp:                    resources/hg19/known_sites/dbsnp_138.b37.vcf.gz
mills:                    resources/hg19/known_sites/Mills_and_1000G_gold_standard.indels.b37.vcf.gz
indels1k:                 resources/hg19/known_sites/1000G_phase1.indels.b37.vcf.gz
snps1k:                   resources/hg19/known_sites/1000G_phase1.snps.high_confidence.b37.vcf.gz
refFlat:                  resources/refFlat.txt

## Conda environment used for running GATK gCNV. Check tool documentation for info on creation.
gatk_conda_env: ~

bed:
  ## Regions of WES capture kit
  WES_probes:   ~
  ## Exonic regions
  WES_strict:   ~
  ## WGS mappable regions
  WGS_mappable: ~

## Paths containing alignments for panel of normal samples
pon:
  WES: resources/PoN/WES
  WGS: resources/PoN/WGS
